#!/bin/bash

cd `dirname $0`
cat > mapnik_config.go <<EOF
package mapnik

// THIS FILE IS AUTO GENERATED BY go generate !DO NOT EDIT!

// #cgo CXXFLAGS: $(mapnik-config --cxxflags) $(mapnik-config --cflags) -Ideps/mapnik-vector-tile/deps/protozero/include -Ideps/mapnik-vector-tile/build/Release/obj/gen -Ideps/mapnik-vector-tile/src -I/usr/local/lib/protozero/include -I/usr/local/opt/icu4c/include
// #cgo CFLAGS: -Ideps/mapnik-vector-tile/deps -Ideps/mapnik-vector-tile/build/Release/obj/gen -Ideps/mapnik-vector-tile/src -I/usr/local/lib/protozero/include -I/usr/local/opt/icu4c/include
// #cgo LDFLAGS: $(mapnik-config --libs) -lboost_system -lprotobuf -L/usr/local/opt/icu4c/lib -licuuc
import "C"

const (
	fontPath   = "$(mapnik-config --fonts)"
	pluginPath = "$(mapnik-config --input-plugins)"
)
EOF

