#!/bin/bash

cd `dirname $0`
cat > mapnik_config.go <<EOF
package mapnik

// THIS FILE IS AUTO GENERATED BY go generate !DO NOT EDIT!

// #cgo CXXFLAGS: $(mapnik-config --cflags) $(pkg-config protobuf --cflags)
// #cgo LDFLAGS: $(mapnik-config --libs) $(mapnik-config --ldflags) $(mapnik-config --dep-libs) -lboost_system $(pkg-config protobuf --libs-only-L) -lprotobuf-lite
import "C"

const (
	fontPath   = "$(mapnik-config --fonts)"
	pluginPath = "$(mapnik-config --input-plugins)"
)
EOF

